sudo: required
dist: trusty

os:
  - linux
  - osx

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - NUGET_XMLDOC_MODE=skip

branches:
  only:
    - master

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8

install:
  - git clone https://github.com/etsy/statsd.git
  - node ./statsd/stats.js ./src/JustEat.StatsD.Tests/statsdconfig.js &

script:
  - ./build.sh
