os: Visual Studio 2017
version: 2.0.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\*AssemblyInfo.*'
  assembly_version: 1.1.1
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  CLI_VERSION: 1.0.1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip
build_script:
  - ps: .\Build.ps1
artifacts:
- path: '**\$(APPVEYOR_PROJECT_NAME)*.nupkg'
  name: Nuget
deploy:
- provider: NuGet
  api_key:
    secure: 6MzbzEs4YdJKS67Gio5gEO8mNKmwfC4UHTCmECZ1KOutI6ndm4vAECazmVNB6an7
  artifact: /.*nupkg/
  on:
    APPVEYOR_REPO_TAG: true
notifications:
- provider: HipChat
  room: 'Eng :: Open Source'
  auth_token:
    secure: eJWABMRPoyfEF9iLzFaTcUEqTc7/64v0FtS1qQe4yhs=
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false
test: off
